//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverQualification
    {
        public int DriverId_FK { get; set; }
        public int StockTypeId_FK { get; set; }
    
        public virtual Driver ADriverQualificationHasOnly1Driver { get; set; }
        public virtual Locomotive ADriverQualificationHasOnly1Locomotive { get; set; }
    }
}
