//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.TrainsDriving = new HashSet<Train>();
            this.TrainsCoDriving = new HashSet<Train>();
            this.DriverHas1orManyQualifications = new HashSet<DriverQualification>();
        }
    
        public int DriverId { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<Train> TrainsDriving { get; set; }
        public virtual ICollection<Train> TrainsCoDriving { get; set; }
        public virtual ICollection<DriverQualification> DriverHas1orManyQualifications { get; set; }
    }
}
