//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.AGoodMakes1OrManyDeliveries = new HashSet<Delivery>();
        }
    
        public int GoodsId { get; set; }
        public string Type { get; set; }
        public decimal UnitWeight { get; set; }
    
        public virtual ICollection<Delivery> AGoodMakes1OrManyDeliveries { get; set; }
    }
}
