//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int GoodsId { get; set; }
        public string Type { get; set; }
        public string Quantity { get; set; }
        public decimal Weight { get; set; }
        public int CollectionFrom { get; set; }
        public int DeliveryTo { get; set; }
        public int TrainId { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual Town CollectionTown { get; set; }
        public virtual Town DeliveryTown { get; set; }
    }
}
