//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RollingStock
    {
        public RollingStock()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int RollingStockId { get; set; }
        public string Class { get; set; }
        public int NumberOwned { get; set; }
        public decimal Length { get; set; }
    
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
