//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.RouteStages = new HashSet<RouteStage>();
        }
    
        public int RouteId { get; set; }
        public int TrainId { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual ICollection<RouteStage> RouteStages { get; set; }
    }
}
