//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStage
    {
        public int RouteId { get; set; }
        public int StageId { get; set; }
        public int VisitSequence { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
