//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.RouteStages = new HashSet<RouteStage>();
        }
    
        public int StageId { get; set; }
        public int From { get; set; }
        public int To { get; set; }
    
        public virtual ICollection<RouteStage> RouteStages { get; set; }
        public virtual Town Town1 { get; set; }
        public virtual Town TownTo { get; set; }
    }
}
