//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.AStationHas1OrManyDeliveriesToBeCollected = new HashSet<Delivery>();
            this.AStationHas1OrManyGoodsDeliveredToIt = new HashSet<Delivery>();
            this.AStationHas1OrManyStagesFromIt = new HashSet<Stage>();
            this.AStationHas1OrManyStagesToIt = new HashSet<Stage>();
            this.AStationCouldHaveManyTrains = new HashSet<Train>();
        }
    
        public int StationId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Delivery> AStationHas1OrManyDeliveriesToBeCollected { get; set; }
        public virtual ICollection<Delivery> AStationHas1OrManyGoodsDeliveredToIt { get; set; }
        public virtual ICollection<Stage> AStationHas1OrManyStagesFromIt { get; set; }
        public virtual ICollection<Stage> AStationHas1OrManyStagesToIt { get; set; }
        public virtual ICollection<Train> AStationCouldHaveManyTrains { get; set; }
    }
}
