//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOnTrain
    {
        public int SerialNumber_FK { get; set; }
        public int TrainId_FK { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual RollingStock RollingStocks { get; set; }
    }
}
