//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockType
    {
        public StockType()
        {
            this.StockTypeHas1orManyRollingStock = new HashSet<RollingStock>();
        }
    
        public int StockTypeId { get; set; }
        public string Class { get; set; }
        public int NumberOwned { get; set; }
        public decimal Length { get; set; }
    
        public virtual ICollection<RollingStock> StockTypeHas1orManyRollingStock { get; set; }
    }
}
