//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public Town()
        {
            this.GoodsCollected = new HashSet<Goods>();
            this.GoodsDelivered = new HashSet<Goods>();
            this.StagesFrom = new HashSet<Stage>();
            this.StageTo = new HashSet<Stage>();
        }
    
        public int TownId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Goods> GoodsCollected { get; set; }
        public virtual ICollection<Goods> GoodsDelivered { get; set; }
        public virtual ICollection<Stage> StagesFrom { get; set; }
        public virtual ICollection<Stage> StageTo { get; set; }
    }
}
