//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainRoutes
    {
        public int TrainRouteId { get; set; }
        public int TrainId { get; set; }
        public int RouteId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
    
        public virtual Train EachTrainRouteHasOnly1RouteOnIt { get; set; }
        public virtual Route EachTrainRouteHasOnly1TrainOnIt { get; set; }
    }
}
