//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFreightRailDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public Train()
        {
            this.ATrainMayContain1OrManyStockOnTrain = new HashSet<StockOnTrain>();
            this.ATrainMayMake1OrManyDeliveries = new HashSet<Delivery>();
            this.ATrainCouldBeOnManyTrainRoutes = new HashSet<TrainRoutes>();
        }
    
        public int TrainId { get; set; }
        public int DriverId_FK { get; set; }
        public int CoDriverId_FK { get; set; }
        public decimal GrossWeight { get; set; }
        public string TotalLength { get; set; }
        public Nullable<int> CurrentStop_FK { get; set; }
    
        public virtual ICollection<StockOnTrain> ATrainMayContain1OrManyStockOnTrain { get; set; }
        public virtual Driver ATrainIsDrivenByOnly1Driver { get; set; }
        public virtual Driver ATrainIsDrivenByOnly1CoDriver { get; set; }
        public virtual ICollection<Delivery> ATrainMayMake1OrManyDeliveries { get; set; }
        public virtual ICollection<TrainRoutes> ATrainCouldBeOnManyTrainRoutes { get; set; }
        public virtual Station ATrainCouldBeAtAStation { get; set; }
    }
}
